 
version: 1.0.{build}

image: Visual Studio 2015

#pull_requests:
#  do_not_increment_build_number: true
  
environment:
  matrix:
  - QTDIR: C:\Qt\5.10.1\msvc2015_64
    BUILD_PLATFORMID: "x64"
  - QTDIR: C:\Qt\5.10.1\msvc2015
    BUILD_PLATFORMID: "x86"

build_script:
  - build.cmd

artifacts:
  - path: '*.zip'
    name: 'hexeditor.%BUILD_PLATFORMID%.%APPVEYOR_BUILD_VERSION%'

deploy:
- provider: GitHub
  description: 'New release of hexeditor'
  auth_token:
    secure: kHdzxX2T86HQf5j9fiIeK0imu96m0/LHJzdSB/wdrNS4JvzCqsQfAsyuIMembQDr
  on:
   appveyor_repo_tag: true
