 
version: 1.0.{build}

image: Visual Studio 2015

skip_non_tags: true

pull_requests:
  do_not_increment_build_number: true
  
configuration: 
   Release

environment:
  matrix:
  - QTDIR: C:\Qt\5.10.1\msvc2015_64
    DEPLOY_FOLDER_NAME: hexeditor.x64
    DEPLOY_INSTALLER_PROJ_NAME: Installer\hexeditor.x64.vdproj
    DEPLOY_INSTALLER_MSI_NAME: Installer\Release.x64
    DEPLOY_INSTALLER_PLATFORMID: "x64"
    DEVENV_EXE: C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\Common7\IDE\devenv.exe
  - QTDIR: C:\Qt\5.10.1\msvc2015
    DEPLOY_FOLDER_NAME: hexeditor.x86
    DEPLOY_INSTALLER_PROJ_NAME: Installer\hexeditor.x86.vdproj
    DEPLOY_INSTALLER_MSI_NAME: Installer\Release.x86
    DEPLOY_INSTALLER_PLATFORMID: "x86"
    DEVENV_EXE: C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\Common7\IDE\devenv.exe

install:
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %QTDIR:msvc=%==%QTDIR% g++ --version
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if %QTDIR:msvc=%==%QTDIR% %make% --version
  - if not %QTDIR:msvc2013=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc2015=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul

before_build:
  - cmd: echo %DEPLOY_INSTALLER_PROJ_NAME%
  - ps: powershell "$env:APPVEYOR_BUILD_FOLDER\version.ps1" -platformId "$env:DEPLOY_INSTALLER_PLATFORMID"
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - qmake -o %APPVEYOR_BUILD_FOLDER%-build -r -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%

build_script:
  #- qmake hexeditor.pro
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - '%make%'

after_build:
  - windeployqt %APPVEYOR_BUILD_FOLDER%-build\%CONFIGURATION%\hexeditor.exe --dir %DEPLOY_FOLDER_NAME%
  - cp %APPVEYOR_BUILD_FOLDER%-build\%CONFIGURATION%\hexeditor.exe %DEPLOY_FOLDER_NAME%
  - cp %APPVEYOR_BUILD_FOLDER%\data\hexeditor_logo.png %DEPLOY_FOLDER_NAME%
  - cp %APPVEYOR_BUILD_FOLDER%\data\hexeditor_logo.ico %DEPLOY_FOLDER_NAME%
  - 7z a "%APPVEYOR_BUILD_FOLDER%\%DEPLOY_FOLDER_NAME%.%APPVEYOR_BUILD_VERSION%.zip" %DEPLOY_FOLDER_NAME%/*
  - cmd: echo '%DEVENV_EXE% %APPVEYOR_BUILD_FOLDER%\%DEPLOY_INSTALLER_PROJ_NAME% /build Release.%DEPLOY_INSTALLER_PLATFORMID%'
  - cmd:      '%DEVENV_EXE% %APPVEYOR_BUILD_FOLDER%\%DEPLOY_INSTALLER_PROJ_NAME% /build Release.%DEPLOY_INSTALLER_PLATFORMID%'
  - 7z a "%APPVEYOR_BUILD_FOLDER%\%DEPLOY_FOLDER_NAME%.%APPVEYOR_BUILD_VERSION%.Installer.zip" %DEPLOY_INSTALLER_MSI_NAME%/*

artifacts:
  - path: '%DEPLOY_FOLDER_NAME%.%APPVEYOR_BUILD_VERSION%.zip'
    name: '%DEPLOY_FOLDER_NAME%.%APPVEYOR_BUILD_VERSION%'
  - path: '%DEPLOY_FOLDER_NAME%.%APPVEYOR_BUILD_VERSION%.Installer.zip'
    name: '%DEPLOY_FOLDER_NAME%.%APPVEYOR_BUILD_VERSION%.Installer'

#deploy:
#- provider: GitHub
#  artifact: %DEPLOY_FOLDER_NAME%.%APPVEYOR_BUILD_VERSION%.zip
#  artifact: %DEPLOY_FOLDER_NAME%.%APPVEYOR_BUILD_VERSION%.Installer.zip
#  auth_token:
#    secure: t8KwiAN0pBg7QNaea4NCDavSO+NpzwADgO/Ir2md9HL1612P2WPV0xNLTaAj3xLM
