 
version: 1.0.{build}

image: Visual Studio 2015

skip_non_tags: true

pull_requests:
  do_not_increment_build_number: true
  
configuration: 
   Release

environment:
  matrix:
  - QTDIR: C:\Qt\5.10.1\msvc2015_64
    BUILD_PLATFORMID: "x64"
  - QTDIR: C:\Qt\5.10.1\msvc2015
    BUILD_PLATFORMID: "x86"

install:
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %QTDIR:msvc=%==%QTDIR% g++ --version
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if %QTDIR:msvc=%==%QTDIR% %make% --version
  - if not %QTDIR:msvc2013=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc2015=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul

build_script:
  - ps: powershell "$env:APPVEYOR_BUILD_FOLDER\version.ps1" -platformId "$env:BUILD_PLATFORMID"
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - qmake -o %APPVEYOR_BUILD_FOLDER%-build -r -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - '%make%'
  - cd %APPVEYOR_BUILD_FOLDER%\Installer
  - windeployqt %APPVEYOR_BUILD_FOLDER%-build\%CONFIGURATION%\hexeditor.exe --dir Installer\Hexeditor
  - cp %APPVEYOR_BUILD_FOLDER%-build\%CONFIGURATION%\hexeditor.exe Installer\Hexeditor
  - cp -a %APPVEYOR_BUILD_FOLDER%\data\. Installer\Hexeditor
  - ps: powershell "$env:APPVEYOR_BUILD_FOLDER\installer.ps1" -platformId "$env:BUILD_PLATFORMID" -cultureId "en-us"
  - 7z a "%APPVEYOR_BUILD_FOLDER%\hexeditor.%BUILD_PLATFORMID%.%APPVEYOR_BUILD_VERSION%.zip"           Installer\Hexeditor\*
  - 7z a "%APPVEYOR_BUILD_FOLDER%\hexeditor.%BUILD_PLATFORMID%.%APPVEYOR_BUILD_VERSION%.Installer.zip" Installer\hexeditor.msi

artifacts:
  - path: '*.zip'
    name: 'hexeditor.%BUILD_PLATFORMID%.%APPVEYOR_BUILD_VERSION%'

deploy:
- provider: GitHub
  description: 'New release of hexeditor'
  auth_token:
    secure: kHdzxX2T86HQf5j9fiIeK0imu96m0/LHJzdSB/wdrNS4JvzCqsQfAsyuIMembQDr
  on:
   appveyor_repo_tag: true
